<?php

/**
 * Computes the value of the position label field on Characters at save time.
 *
 * @see _computed_field_compute_value()
 */
function computed_field_field_position_label_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  // The position label is the Position value and Custom Position value,
  // concatenated with an &.

  $positions = array();

  // Currently the field is configured to be single-value, but just to be
  // on the safe side we'll treat it as multi-value.
  $tids = array();
  foreach (field_get_items($entity_type, $entity, 'field_position') as $term) {
    $tids[] = $term['tid'];
  }

  foreach (taxonomy_term_load_multiple($tids) as $term) {
    $positions[] = entity_label('taxonomy_term', $term);
  }
  foreach (field_get_items($entity_type, $entity, 'field_position_custom') as $custom_position) {
    $positions[] = $custom_position['value'];
  }

  // Compress all of the position values together into a string.
  // Figuring out the structure of this value array took way longer than it
  // should have. Documentation EPIC FAIL!
  $entity_field[0]['value'] = implode(' & ', $positions);
}

/**
 * Computes the display of the position label field on Charaters, at view time.
 *
 * @see computed_field_field_formatter_view()
 */
function computed_field_field_position_label_display($field, $entity_field_item, $entity_lang, $langcode) {
  return check_plain($entity_field_item['value']);
}

/**
 * Computes the value of the character label field on Notes at save time.
 *
 * @see _computed_field_compute_value()
 * @todo Actually put code here.
 */
function computed_field_field_character_label_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  // The character label is the Rank, name, and position of the character at the
  // time the node is saved.  Note that the character hast o be loaded via a
  // reference field.

}

/**
 * Computes the display of the position label field on Charaters, at view time.
 *
 * @see computed_field_field_formatter_view()
 * @todo Actually put code here. Probably just display it literally.
 */
function computed_field_field_character_label_display($field, $entity_field_item, $entity_lang, $langcode) {
  return check_plain($entity_field_item['value']);
}
